python:
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cpython
  - 3.14.* *_cpython

numpy:
  - 1.22
  - 1.22
  - 1.23
  - 1.24
  - 1.26
  - 2.0
  - 2.1

docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64

zip_keys:
  - - python
    - numpy