python:
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython

numpy:
  - 1.22
  - 1.22
  - 1.23
  - 1.24
  - 1.26

c_stdlib:
  - sysroot                # [linux]
  - macosx_deployment_target  # [osx]
  - vs2017_win-64          # [win]

c_stdlib_version:         # [unix]
  - 2.17                  # [linux]
  - 10.13                 # [osx]

docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64

zip_keys:
  - - python
    - numpy